### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aamesaa** [aamesaa/beasiswa#2]
- [x] Hapus CheckBox di Modal saat edit Beasiswa
- [x] Tampilkan Sisa Pinjaman di Modal Detail&Tambah di Pinjaman
- [x] Check Session
- [x] Tampilin pecahan ribuan di nominal  > Search Google
- [x] Tombol lihat syarat, langsung download atau buka file ?
- [x] Ubah tampilan di detail Pendaftar (syarat yg perlu download dijadikan link)
- [x] Re-check download (Can't open file)
- [x] Add download report

**Comment by charolinesepta97** [comment]
Hapus Check Box Done

**Comment by charolinesepta97** [comment]
Separator done
